- name: agregar tomcat group
  group:
    name: tomcat
  becom: true
  when: ansible_os_family == "RedHat"

- name: agregar "tomcat" aser
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes
  become: true
  when: ansible_os_family == "RedHat"

- name: descargar tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"
  become: true
  when: ansible_os_family == "RedHat"

- name: create tomcat directory
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat
  become: true
  when: ansible_os_family =="RedHat"

- name: extract tomcat
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: / usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /usr/share/tomcat/bin
  become: true
  when: ansible_os_family == "RedHat"

- name: copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_Service_mgr == "systemd"

- name: start tomcat
  ansible.builtin.command: systemctl start tomcat.service
  become: true
  when: ansible_os_family =="RedHat"
